[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
backgroundColor = "black"
primaryColor = "rgb(0, 157, 224)"
secondaryBackgroundColor = "rgba(255, 255, 255, 0.13)"
textColor = "white"
